services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
  test-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: todo_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
  
  app:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0.0
      - DB_URL=jdbc:postgresql://db:5432/todo_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
volumes:
  postgres_data: